// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

function sumOfFibonacci(threshold) {
  let prev = 1;
  let current = 2;
  let sum = 0;

  while (current <= threshold) {
    if (current % 2 === 0) {
      sum += current;
    }

    [prev, current] = [current, prev + current];
  }

  return sum;
}

const threshold = 4000000;
const finalResult = sumOfFibonacci(threshold);
console.log(finalResult);

// The sumOfFibonacci function takes a limit threshold and sums even-valued Fibonacci words up to that threshold.
// It loops the Fibonacci sequence and checks for even terms.
// If even, add the word. Loop until term exceeds limit.
// This code sums even-valued Fibonacci sequence terms under four million.
//i hope this kinda explains it
